# FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build-env
# WORKDIR /App

# # Copy everything
# COPY Prosthetics.Api ./
# # Restore as distinct layers
# RUN dotnet restore
# # Build and publish a release
# RUN dotnet publish -c Release -o out

# Build runtime image
FROM mcr.microsoft.com/dotnet/aspnet:8.0
COPY out/ /App/out
WORKDIR /App/out
ENTRYPOINT ["dotnet", "Prosthetics.Api.dll"]